# This is an action intended to deploy commited code to the server currently hosting Bacon-Bot

name: deployment

# Runs the workflow on push to repo
on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:      
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
          
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts
          
      - name: Deploy code with git
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: 'opc@${{ secrets.SSH_HOST }}'
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          command: cd /usr/local/bin/baconbot2 && git pull origin master

      - name: Update dependencies
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: 'opc@${{ secrets.SSH_HOST }}'
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          command: cd /usr/local/bin/baconbot2 && sudo npm install
        
      - name: Change dir permissions
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: 'opc@${{ secrets.SSH_HOST }}'
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          command: sudo chmod -R 777 /usr/local/bin/baconbot2
          
      - name: Redeploy commands
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: 'opc@${{ secrets.SSH_HOST }}'
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          command: cd /usr/local/bin/baconbot2 && sudo node deploy-commands.js

      - name: Restart baconbot.service
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: 'opc@${{ secrets.SSH_HOST }}'
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          command: cd /usr/local/bin/baconbot2 && sudo systemctl restart baconbot2.service
